### ISSUE TITLE
Remove the need to import anchor-lang as dependency for components and systems

### ISSUE THREAD

**Issue by GabrielePicco** [magicblock-labs/bolt#28]
**Is your feature request related to a problem? Please describe.**
Currently, components and systems import both anchor-lang and bolt-lang

**Describe the solution you'd like**
Since bolt-lang has a dependency to anchor-lang, needed functions and macros can be re-exported to avoid the anchor-lang dependency on components and systems

**Comment by notdanilo** [comment]
Would it be related to #114?
